id: I5499916D
ocr_import_info:
  timestamp: '2023-09-23T05:45:46.741894+00:00'
  batch_id: batch-c3e1
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-23 06:43:54.052763+00:00
last_modified: 2023-09-23 06:43:54.052770+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3374
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3374
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་ཁས་ལེན་གྱི་རྒྱུན་འཐོར་བུ་རྣ་ལམ་དུ་འབྱུང་བ་རྣམས་ཕྱོགས་གཅིག་ཏུ་བཀོད་པ་སོགས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9127187267486986
  ocr_word_median_confidence_index: 0.97618604
bases:
  I1NLM3374_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3374_001
      total_pages: 244
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3374_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.97618604
      ocr_word_mean_confidence_index: 0.9127187267486986
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
